# -*- coding: utf-8 -*-
"""Conversor Juche

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L6YMSxU0Kpczch3_MQwcQvkjv80skRoP

# 📅 **Conversor Juche**
### ¿Qué año es en Corea del Norte?
"""

# 👉 Dale play al script y esperá que aparezca un check de color verde que indica que se ha cargado la función

def conversor_juche():

    while True:

        gregoriano = int(input("Ingresá un año del calendario gregoriano y presioná enter: "))
        juche = gregoriano - 1911

        if gregoriano >= 1912 and gregoriano <= 2023:
          print(f"El año {gregoriano} del calendario gregoriano equivale al año {juche} del calendario Juche.")

        elif gregoriano >= 2024:
          print(f"El año {gregoriano} del calendario gregoriano, en un futuro, equivaldría al año {juche} del calendario Juche.")

        else:
          print("Los años anteriores a 1912, en Corea del Norte, se computan en calendario gregoriano.")
          print("En el calendario Juche no existe ni el año 0 ni el equivalente al a.C.")

        loop = input("¿Querés convertir otro año? Sí o No: ")
        
        if loop == "No" or loop == "nO" or loop == "NO" or loop == "no":
          print("📅 ¡Muchas gracias por usar el conversor Juche! 📅")
          break

    return None

# 🤙 Dale play a la función y empezá a convertir años entre calendarios

conversor_juche()